### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{

  "userId" : 1,
  "accountNumber" : "1000000001",
  "amount" : 1233
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId" : "f1d4f257458f408aba3690e124326916",
  "accountNumber" : "1000000001",
  "amount" : 1233
}

### query transaction
GET http://localhost:8080/transaction/f1d4f257458f408aba3690e124326916